In [5]:
import pandas as pd
df = pd.read_pickle("netflix_cleaned.pkl")

In [6]:
print(df.isnull().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
parsed_date       98
dtype: int64

In [7]:
print(df.fillna(df['director']=='unknown'))

     show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description parsed_date
0     As her father nears the end of his life, filmm...  2021-09-25
1     After crossing paths at a party, a Cape Town t...  2021-09-24
2     To protect his family from a powerful drug lor...  2021-09-24
3     Feuds, flirtations and toilet talk go down amo...  2021-09-24
4     In a city of coaching centers known to train I...  2021-09-24
...                                                 ...         ...
8802  A political cartoonist, a crime reporter and a...  2019-11-20
8803  While living alone in a spooky town, a young g...  2019-07-01
8804  Looking to survive in a world taken over by zo...  2019-11-01
8805  Dragged from civilian life, a former superhero...  2020-01-11
8806  A scrappy but poor boy worms his way into a ty...  2019-03-02

[8807 rows x 13 columns]

In [8]:
print(df.isnull().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
parsed_date       98
dtype: int64

In [9]:
def remove_nulls(df, cols):
    return df.dropna(subset = cols)

df = remove_nulls(df, ["director", "cast", "country", "date_added", "rating", "duration", "parsed_date"])

In [10]:
print(df.isnull().sum())

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
parsed_date     0
dtype: int64

In [11]:
df['director'].head

<bound method NDFrame.head of 7              Haile Gerima
8           Andy Devonshire
9            Theodore Melfi
12      Christian Schwochow
24               S. Shankar
               ...
8801        Majid Al Ansari
8802          David Fincher
8804        Ruben Fleischer
8805           Peter Hewitt
8806            Mozez Singh
Name: director, Length: 5328, dtype: object>

In [12]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [13]:
print(df['director'])

7                                            Haile Gerima
8                                         Andy Devonshire
9                                          Theodore Melfi
12                                    Christian Schwochow
24                                             S. Shankar
27                                           Dennis Dugan
28                                          Scott Stewart
29                                         Robert Luketic
38                                           George Nolfi
41                                       Steven Spielberg
42                                         Jeannot Szwarc
43                                              Joe Alves
44                                         Joseph Sargent
46                                        Daniel Espinosa
48                                          Antoine Fuqua
51                                      Toshiya Shinohara
52                                      Toshiya Shinohara
53                                      Toshiya Shinohara
54                                      Toshiya Shinohara
56                                        Masahiko Murata
57                                        Hajime Kamegaki
58                                        Masahiko Murata
59                                        Hajime Kamegaki
60                                        Masahiko Murata
61                                     Hirotsugu Kawasaki
62                                        Toshiyuki Tsuru
63                                         Tensai Okamura
73                                           Kemi Adetiba
81                                  Cedric Nicolas-Troyan
84                             JJC Skillz, Funke Akindele
90                                       Alice Waddington
94                                           Raja Gosnell
96                                          Stephen Kijak
105                                  Lijo Jose Pellissery
107                                          David de Vos
114                                          Rahul Rawail
115                                          Jane Campion
116                                       Nagesh Kukunoor
118                                         Shanker Raman
122                                          Jane Campion
126                                    Vidhu Vinod Chopra
127                                           Mark Rosman
129                                       Lasse Hallström
131                                          Ridley Scott
133                                        Neill Blomkamp
134                                         Phillip Noyce
135                                          Renny Harlin
136                                     Anthony Minghella
137                                          Simon Wincer
138                                       Lasse Hallström
139                                             Spike Lee
140                                    Sebastián Schindel
141                                      Steven C. Miller
142                                   Richard LaGravenese
143                                       Martin Campbell
144                                       Reginald Hudlin
145                          George Jackson, Doug McHenry
146                                             Eric Meza
149                                        Michael Martin
150                                         Michael Rymer
151                        Andrew Lau Wai-keung, Alan Mak
152                                          Brett Weiner
155                                            Jim Henson
156                                           Gary Winick
157                                    Danishka Esterhazy
158                                             Troy Byer
159                                        Pang Ho-cheung
161                                            Tim Burton
162                                       Reginald Hudlin
163                                          David Zucker
164                                           Kinka Usher
166                                          Sergio Leone
167                   Matthew O'Callaghan, Todd Wilderman
168                        Bobby Farrelly, Peter Farrelly
169                                     Wolfgang Petersen
170                                          Peter Spirer
171                                        Michael Carney
172                                     Richard Linklater
173                                              Amy Rice
174                                         Antoine Fuqua
175                                        Randal Kleiser
176                                       Michael Ritchie
177                                       J. Lee Thompson
178                             Evan Goldberg, Seth Rogen
179                                           Tom Shadyac
182                                        Malcolm D. Lee
183                                     Wolfgang Petersen
188                               Ramzy Bedia, Éric Judor
190                                     Sharan Koppisetty
191                                       Taylor Sheridan
192                                          Sachin Yardi
195                                         Saurabh Kabra
198                                          Kemi Adetiba
199                                          Partho Mitra
200                                         Santram Varma
201                            Anil V. Kumar, Anurag Basu
202                                        Sangeeth Sivan
203                                          Umesh Ghadge
204                                          Sachin Yardi
205                                          David Dhawan
206                                      Dibakar Banerjee
207                                        Apoorva Lakhia
208                                         Milan Luthria
209                                         Milan Luthria
210                                       Pawan Kripalani
211                                         Bhushan Patel
215                                        Apoorva Lakhia
216                            Raj Nidimoru, Krishna D.K.
217                                         Milan Luthria
227                                 Angel Kristi Williams
228                                       Roger Donaldson
229                                   Christopher Alender
231                                         David Oyelowo
247                                  Brian Andrew Mendoza
251                                         Drake Doremus
253                                           Mani Ratnam
259                                       Paakhi Tyrewala
264                                           Steve Brill
267                                          Jane Campion
270                            Ferdinando Cito Filomarino
273                                    Juan Carlos Medina
276                                         Inma Torrente
278                                        Julián Gaviria
279                                       Steven Yamamoto
281                                       Charles Uwagbai
282                                      Julián Hernández
284                                        Vince Marcello
285                                    Jonathan Teplitzky
292                                        Dustin Hoffman
293                                             Adze Ugah
295                                         Quoc Bao Tran
297     Bejoy Nambiar, Priyadarshan, Karthik Narain, V...
298                                          Kayode Kasum
299                                        Just Philippot
300                        Kirk DeMicco, Brandon Jeffords
301                                          Rohit Shetty
303                                       Alejandro Doria
304                                         Laura Fairrie
305                                       Marcelo Piñeyro
306                                            Izu Ojukwu
307                                         Peter Winther
308                                            Susan Lacy
314                                         James Mangold
315                                       Chineze Anyaene
316                                           Hsu Fu-chun
325                                          Brian Levant
326                                            Rod Daniel
327                                       Robert Zemeckis
328                                       Todor Chapkanov
329                                      Steven Spielberg
330                         Phil Lord, Christopher Miller
332                                          Renny Harlin
333                                           John Hughes
334                                        Justin Baldoni
335                                              Joe Roth
337                                         Mark Helfrich
340                                     Christopher Nolan
341                                  Paul Thomas Anderson
342                                           Nick Castle
343                                          Howard Zieff
344                                          Howard Zieff
345                                           David Feiss
346                                    David Gordon Green
347                                          Jorge Blanco
348                                            Zara Hayes
349                                             Gary Ross
350                                        Clint Eastwood
351                                           Trey Parker
352                                    Kelly Fremon Craig
353                                            Tom Elkins
354                                            Tony Scott
355                                           Brad Furman
356                                         Sylvain White
357                                         Brad Anderson
358                                         Irwin Winkler
359                                             Spike Lee
360                                        Garry Marshall
365                                          Najwa Najjar
374                                        Michelle Bello
377                                      Daniel Markowicz
380                                           Glen Winter
383                                       Ram Gopal Varma
389                                           Yuval Adler
392                                     Quentin Tarantino
393                                             Clay Glen
402                                    Augustine Frizzell
410                                         Rajiv Chilaka
415                                         Rajiv Chilaka
426                   Ainsley Gardiner, Briar Grace-Smith
429                                         Seyi Babatope
433                                         Morgan Ingari
436                                   Abdulaziz Alshlahei
437                                          Edward Drake
439     Sita Likitvanichkul, Jetarin Ratanaserikiat, A...
445                                         Sofia Coppola
446                                       Colin Trevorrow
447                                           Bill Condon
448                                           Bill Condon
449                                           David Slade
450                                           Chris Weitz
451                                   Catherine Hardwicke
452                                     Hadrah Daeng Ratu
460                               Ash Brannon, Chris Buck
463                       Roberto De Feo, Paolo Strippoli
469                                          Semi Chellas
474                                       Nima Nourizadeh
486                         Jericca Cleland, Kevin Munroe
489                                        Ahmed Siddiqui
491                                   Hallie Meyers-Shyer
492                                           Scott Speer
494                                        Barry Levinson
496                                     Camille Delamarre
502                                   Mahmood Ali-Balogun
503                                          Jan Holoubek
506                                        Christine Luby
508                                          Yeo Siew Hua
518                                          Hardik Mehta
528                     Rajveer Singh Maan, Harpeet Singh
529                                       Youssef Chahine
531      Saw Teong Hin, Nik Amir Mustapha, M.S. Prem Nath
534                                            Rano Karno
541                                          Pramod Pawar
542                                         Naresh Saigal
551                                          Vinil Mathew
554                                          Ramsey Nouah
555                                          Bong Joon Ho
556                                         Kim Tae-hyung
557                        Michael Spierig, Peter Spierig
558                                       Ernie Barbarash
559                                     Wolfgang Petersen
561                                             Jay Roach
562                                             Jay Roach
563                                             Jay Roach
564                                  Paul Thomas Anderson
566                                                   McG
567                                        Frank Marshall
568                                           Nick Castle
569                                             Victor Vu
572                                          Joel Hopkins
573                          John Stevenson, Mark Osborne
574                                   Jennifer Yuh Nelson
575                                         Greg Berlanti
576                                           Garth Davis
578                                          Rob Marshall
579                                          Martin Brest
581                                    Paul W.S. Anderson
582                                        Garry Marshall
583                                          Ivan Reitman
584                                           Joel Gallen
585                                       Claire McCarthy
589                                           Trevor Nunn
591                                      Gabriele Muccino
592                                       Jim Field Smith
593                                            Chris Koch
594                                           J.J. Abrams
595                                           Rob Minkoff
596                                          Lynn Shelton
597                                            Adam McKay
598                                         Anton Corbijn
599                                         Robin Bissell
600                                         David Fincher
601                                      John G. Avildsen
602                                      John G. Avildsen
603                                      John G. Avildsen
604                                           Alan Parker
605                                           Walter Hill
606                                        Stephen Frears
607                                         Bryan Bertino
608                                   Phil Alden Robinson
609                      Florian Henckel von Donnersmarck
610                                           Len Wiseman
611                             Måns Mårlind, Björn Stein
612                                    Patrick Tatopoulos
613                                      Robert O. Peters
614                                          Vincent Ward
615                                          Gregory Nava
618                                         Matt Thompson
622                                          Matt Aselton
630                                        Andrew Dominik
634                                      Anissa Bonnefont
635                                          Bahij Hojeij
636                                    Jonathan Hensleigh
643                                       Justin P. Lange
650                                       Jayme Monjardim
651                                        Kingsley Ogoro
654                                        Cristina Jacob
655                                        Cristina Jacob
656                                        Cristina Jacob
676                                       Rob Seidenglanz
681                                       Simon Frederick
685                                            Paul Weitz
688                                          Kayode Kasum
694                                        Soudade Kaadan
698                                    Antoinette Jadaone
701                                        Marie Clements
702                                      David O. Russell
705                                              Max Jabs
708                                  Ricardo de Montreuil
711                                         Peter Chelsom
716                                       Francine Parker
718                                      Daniel Schechter
721                                          Mike Gunther
722                                          David Zeiger
723                                         Michael Simon
726                         Joe Berlinger, Bruce Sinofsky
728                                        Bradley Parker
735                                           Prabhakaran
736                                      Manjari Makijany
737                                             Jay Oliva
739                                       Chris Appelhans
740                                        Michael Tiddes
741                                             Lara Saba
742                                     Bao Nhan, Namcito
743                                             Mark Raso
745                                         Tariq Alkazim
746                                             Mark Raso
747                                         Kenneth Gyang
750                                       Yulene Olaizola
752                                           Mark Waters
754                                      Matthew Heineman
756                                         Robert Peters
757                                         Jonathan Clay
758                                           Ally Pankiw
762                                         Lee Kae-byeok
764                                         Jayan Moodley
765                                       Daniel Benmayor
766                                             Alex Díaz
768                                      Helena Bergström
770                                          Myriam Fares
773                                               Rae Red
774                                            Lance Hool
775                                           Nicole Conn
776                                          Les Mayfield
777                            Ellen Seidler, Megan Siler
779                                       Roger Christian
782                                           Lance Young
783                                          Leandro Neri
784                                       Thom Fitzgerald
786                                      Don Michael Paul
787                                    Andrzej Bartkowiak
788                                         Harold Becker
790                                          Andrew Jenks
791                                       Ric Roman Waugh
792                                            Rob Reiner

In [14]:
df['listed_in'].apply(lambda x:[i.replace(" ","") for i in x.split(",")])

7        [Dramas, IndependentMovies, InternationalMovies]
8                             [BritishTVShows, RealityTV]
9                                      [Comedies, Dramas]
12                          [Dramas, InternationalMovies]
24        [Comedies, InternationalMovies, RomanticMovies]
27                                             [Comedies]
28                         [HorrorMovies, Sci-Fi&Fantasy]
29                                            [Thrillers]
38                             [Action&Adventure, Dramas]
41              [Action&Adventure, ClassicMovies, Dramas]
42                      [Dramas, HorrorMovies, Thrillers]
43            [Action&Adventure, HorrorMovies, Thrillers]
44            [Action&Adventure, HorrorMovies, Thrillers]
46                                     [Action&Adventure]
48                                    [Dramas, Thrillers]
51      [Action&Adventure, AnimeFeatures, Internationa...
52      [Action&Adventure, AnimeFeatures, Internationa...
53      [Action&Adventure, AnimeFeatures, Internationa...
54      [Action&Adventure, AnimeFeatures, Internationa...
56      [Action&Adventure, AnimeFeatures, Internationa...
57      [Action&Adventure, AnimeFeatures, Internationa...
58      [Action&Adventure, AnimeFeatures, Internationa...
59      [Action&Adventure, AnimeFeatures, Internationa...
60      [Action&Adventure, AnimeFeatures, Internationa...
61      [Action&Adventure, AnimeFeatures, Internationa...
62      [Action&Adventure, AnimeFeatures, Internationa...
63      [Action&Adventure, AnimeFeatures, Internationa...
73                          [Dramas, InternationalMovies]
81                                     [Action&Adventure]
84                   [Action&Adventure, Comedies, Dramas]
90                            [Sci-Fi&Fantasy, Thrillers]
94                      [Children&FamilyMovies, Comedies]
96                        [Documentaries, Music&Musicals]
105                  [Action&Adventure, Comedies, Dramas]
107                       [Children&FamilyMovies, Dramas]
114              [Dramas, InternationalMovies, Thrillers]
115                              [Dramas, RomanticMovies]
116                 [Comedies, Dramas, IndependentMovies]
118              [Dramas, InternationalMovies, Thrillers]
122                                           [Thrillers]
126         [Dramas, InternationalMovies, RomanticMovies]
127                     [Children&FamilyMovies, Comedies]
129                                              [Dramas]
131         [Action&Adventure, ClassicMovies, CultMovies]
133                    [Action&Adventure, Sci-Fi&Fantasy]
134                            [Action&Adventure, Dramas]
135                                    [Action&Adventure]
136                              [Dramas, RomanticMovies]
137                          [Action&Adventure, Comedies]
138                              [Dramas, RomanticMovies]
139                     [ClassicMovies, Comedies, Dramas]
140              [Dramas, InternationalMovies, Thrillers]
141                                    [Action&Adventure]
142                                              [Dramas]
143                    [Action&Adventure, Sci-Fi&Fantasy]
144                                [Comedies, CultMovies]
145                [Comedies, CultMovies, Music&Musicals]
146                            [Comedies, Music&Musicals]
149                          [Action&Adventure, Comedies]
150                                           [Thrillers]
151               [Action&Adventure, InternationalMovies]
152                                            [Comedies]
155     [Action&Adventure, Children&FamilyMovies, Cult...
156                    [Comedies, Dramas, RomanticMovies]
157                           [Sci-Fi&Fantasy, Thrillers]
158                            [Comedies, RomanticMovies]
159               [Comedies, Dramas, InternationalMovies]
161                [Comedies, CultMovies, Sci-Fi&Fantasy]
162                                              [Dramas]
163                            [Comedies, RomanticMovies]
164                          [Action&Adventure, Comedies]
166                               [ClassicMovies, Dramas]
167                     [Children&FamilyMovies, Comedies]
168     [Action&Adventure, Children&FamilyMovies, Come...
169                            [Action&Adventure, Dramas]
170                       [Documentaries, Music&Musicals]
171                          [Dramas, Faith&Spirituality]
172                            [Comedies, Music&Musicals]
173                          [Documentaries, LGBTQMovies]
174                            [Action&Adventure, Dramas]
175                              [Dramas, RomanticMovies]
176                          [Action&Adventure, Comedies]
177                     [Action&Adventure, ClassicMovies]
178                          [Action&Adventure, Comedies]
179                            [Comedies, RomanticMovies]
182                                            [Comedies]
183                     [Action&Adventure, ClassicMovies]
188                       [Comedies, InternationalMovies]
190                         [Dramas, InternationalMovies]
191                           [Dramas, IndependentMovies]
192     [Action&Adventure, Comedies, InternationalMovies]
195               [Comedies, Dramas, InternationalMovies]
198        [CrimeTVShows, InternationalTVShows, TVDramas]
199               [Comedies, Dramas, InternationalMovies]
200     [Action&Adventure, HorrorMovies, International...
201              [Dramas, InternationalMovies, Thrillers]
202       [Comedies, InternationalMovies, Music&Musicals]
203                       [Comedies, InternationalMovies]
204                       [Comedies, InternationalMovies]
205       [Comedies, InternationalMovies, Sci-Fi&Fantasy]
206      [Dramas, IndependentMovies, InternationalMovies]
207     [Action&Adventure, InternationalMovies, Music&...
208         [Dramas, InternationalMovies, Music&Musicals]
209         [Dramas, InternationalMovies, Music&Musicals]
210                   [HorrorMovies, InternationalMovies]
211                   [HorrorMovies, InternationalMovies]
215       [Action&Adventure, Dramas, InternationalMovies]
216                 [Comedies, Dramas, IndependentMovies]
217               [Comedies, Dramas, InternationalMovies]
227           [Dramas, IndependentMovies, RomanticMovies]
228                                    [Action&Adventure]
229                                        [HorrorMovies]
231                       [Children&FamilyMovies, Dramas]
247                            [Action&Adventure, Dramas]
251           [Dramas, IndependentMovies, RomanticMovies]
253         [Dramas, InternationalMovies, RomanticMovies]
259               [Comedies, Dramas, InternationalMovies]
264                         [Comedies, IndependentMovies]
267            [ClassicMovies, Dramas, IndependentMovies]
270                                    [Action&Adventure]
273        [CrimeTVShows, InternationalTVShows, TVDramas]
276     [InternationalTVShows, RomanticTVShows, Spanis...
278                                      [Stand-UpComedy]
279     [Action&Adventure, AnimeFeatures, Children&Fam...
281                       [Comedies, InternationalMovies]
282      [Dramas, IndependentMovies, InternationalMovies]
284                            [Comedies, RomanticMovies]
285                         [Dramas, InternationalMovies]
292                 [Comedies, Dramas, IndependentMovies]
293       [Comedies, InternationalMovies, RomanticMovies]
295                          [Action&Adventure, Comedies]
297                                             [TVShows]
298               [Comedies, Dramas, InternationalMovies]
299     [HorrorMovies, IndependentMovies, Internationa...
300               [Children&FamilyMovies, Music&Musicals]
301     [Action&Adventure, Comedies, InternationalMovies]
303           [Comedies, CultMovies, InternationalMovies]
304                                       [Documentaries]
305          [ClassicMovies, Dramas, InternationalMovies]
306                         [Dramas, InternationalMovies]
307                                        [HorrorMovies]
308                                              [Movies]
314           [Dramas, IndependentMovies, RomanticMovies]
315                         [Dramas, InternationalMovies]
316     [InternationalTVShows, RomanticTVShows, TVCome...
325                     [Children&FamilyMovies, Comedies]
326                     [Children&FamilyMovies, Comedies]
327                    [Action&Adventure, Sci-Fi&Fantasy]
328                                    [Action&Adventure]
329                                              [Dramas]
330     [Children&FamilyMovies, Comedies, Sci-Fi&Fantasy]
332      [Action&Adventure, HorrorMovies, Sci-Fi&Fantasy]
333                 [ClassicMovies, Comedies, CultMovies]
334                              [Dramas, RomanticMovies]
335                                   [Dramas, Thrillers]
337                            [Comedies, RomanticMovies]
340         [Action&Adventure, Sci-Fi&Fantasy, Thrillers]
341                           [Dramas, IndependentMovies]
342                                            [Comedies]
343                                              [Dramas]
344             [Children&FamilyMovies, Comedies, Dramas]
345                     [Children&FamilyMovies, Comedies]
346                          [Action&Adventure, Comedies]
347     [Children&FamilyMovies, Comedies, Sci-Fi&Fantasy]
348                                            [Comedies]
349                                [Dramas, SportsMovies]
350            [Action&Adventure, Dramas, Sci-Fi&Fantasy]
351              [Action&Adventure, Comedies, CultMovies]
352                                    [Comedies, Dramas]
353                                        [HorrorMovies]
354                          [Action&Adventure, Comedies]
355                                   [Dramas, Thrillers]
356                                    [Action&Adventure]
357                [Dramas, IndependentMovies, Thrillers]
358                                           [Thrillers]
359                                      [Stand-UpComedy]
360                            [Comedies, RomanticMovies]
365      [Dramas, IndependentMovies, InternationalMovies]
374       [Comedies, InternationalMovies, RomanticMovies]
377               [Action&Adventure, InternationalMovies]
380     [CrimeTVShows, TVAction&Adventure, TVSci-Fi&Fa...
383               [Action&Adventure, InternationalMovies]
389              [Dramas, InternationalMovies, Thrillers]
392                            [Action&Adventure, Dramas]
393                 [Children&FamilyMovies, SportsMovies]
402                              [Dramas, RomanticMovies]
410                               [Children&FamilyMovies]
415                               [Children&FamilyMovies]
426                                              [Dramas]
429              [Dramas, InternationalMovies, Thrillers]
433                 [Comedies, Dramas, IndependentMovies]
436         [Dramas, InternationalMovies, RomanticMovies]
437                                    [Action&Adventure]
439              [Dramas, InternationalMovies, Thrillers]
445                [Dramas, IndependentMovies, Thrillers]
446                                              [Dramas]
447                              [Dramas, RomanticMovies]
448                              [Dramas, RomanticMovies]
449                              [Dramas, RomanticMovies]
450                              [Dramas, RomanticMovies]
451            [Action&Adventure, Dramas, RomanticMovies]
452               [Comedies, Dramas, InternationalMovies]
460       [Children&FamilyMovies, Comedies, SportsMovies]
463                   [HorrorMovies, InternationalMovies]
469                           [Dramas, IndependentMovies]
474                          [Action&Adventure, Comedies]
486     [Children&FamilyMovies, Comedies, Sci-Fi&Fantasy]
489                       [Comedies, InternationalMovies]
491                    [Comedies, Dramas, RomanticMovies]
492                              [Dramas, RomanticMovies]
494                            [Comedies, Music&Musicals]
496               [Action&Adventure, InternationalMovies]
502         [Dramas, InternationalMovies, RomanticMovies]
503        [CrimeTVShows, InternationalTVShows, TVDramas]
506                 [InternationalMovies, RomanticMovies]
508                         [Dramas, InternationalMovies]
518                         [Dramas, InternationalMovies]
528         [Dramas, InternationalMovies, RomanticMovies]
529                         [Dramas, InternationalMovies]
531                         [Dramas, InternationalMovies]
534                         [Dramas, InternationalMovies]
541               [Comedies, Dramas, InternationalMovies]
542                         [Dramas, InternationalMovies]
551      [InternationalMovies, RomanticMovies, Thrillers]
554              [Dramas, InternationalMovies, Thrillers]
555     [Action&Adventure, CultMovies, InternationalMo...
556        [HorrorMovies, InternationalMovies, Thrillers]
557                        [HorrorMovies, Sci-Fi&Fantasy]
558                                    [Action&Adventure]
559                                    [Action&Adventure]
561                          [Action&Adventure, Comedies]
562                                            [Comedies]
563          [Action&Adventure, Comedies, Sci-Fi&Fantasy]
564                 [Comedies, Dramas, IndependentMovies]
566                          [Action&Adventure, Comedies]
567                         [Action&Adventure, Thrillers]
568                     [Children&FamilyMovies, Comedies]
569         [Dramas, InternationalMovies, RomanticMovies]
572               [Comedies, Dramas, InternationalMovies]
573                     [Children&FamilyMovies, Comedies]
574                     [Children&FamilyMovies, Comedies]
575                    [Comedies, Dramas, RomanticMovies]
576     [Dramas, Faith&Spirituality, InternationalMovies]
578                              [Dramas, RomanticMovies]
579           [Action&Adventure, ClassicMovies, Comedies]
581                    [Action&Adventure, Sci-Fi&Fantasy]
582                                    [Comedies, Dramas]
583                            [Comedies, RomanticMovies]
584                                            [Comedies]
585                              [Dramas, RomanticMovies]
589                         [Dramas, InternationalMovies]
591                              [Dramas, RomanticMovies]
592                            [Comedies, RomanticMovies]
593                     [Children&FamilyMovies, Comedies]
594                    [Action&Adventure, Sci-Fi&Fantasy]
595                     [Children&FamilyMovies, Comedies]
596                 [Comedies, Dramas, IndependentMovies]
597            [Action&Adventure, Comedies, SportsMovies]
598                                   [Dramas, Thrillers]
599                                              [Dramas]
600                                           [Thrillers]
601     [Action&Adventure, Children&FamilyMovies, Clas...
602     [Action&Adventure, Children&FamilyMovies, Dramas]
603                       [Children&FamilyMovies, Dramas]
604                                              [Dramas]
605                                    [Action&Adventure]
606                         [Dramas, InternationalMovies]
607                             [HorrorMovies, Thrillers]
608                                    [Action&Adventure]
609                    [Action&Adventure, RomanticMovies]
610      [Action&Adventure, HorrorMovies, Sci-Fi&Fantasy]
611      [Action&Adventure, HorrorMovies, Sci-Fi&Fantasy]
612      [Action&Adventure, HorrorMovies, Sci-Fi&Fantasy]
613              [Dramas, InternationalMovies, Thrillers]
614              [Dramas, RomanticMovies, Sci-Fi&Fantasy]
615              [Dramas, Music&Musicals, RomanticMovies]
618                          [Action&Adventure, Comedies]
622                                           [Thrillers]
630                                              [Dramas]
634                  [Documentaries, InternationalMovies]
635                         [Dramas, InternationalMovies]
636                                    [Action&Adventure]
643                                        [HorrorMovies]
650                         [Dramas, InternationalMovies]
651               [Comedies, Dramas, InternationalMovies]
654               [Comedies, Dramas, InternationalMovies]
655               [Comedies, Dramas, InternationalMovies]
656     [InternationalMovies, Music&Musicals, Romantic...
676                 [CrimeTVShows, TVDramas, TVMysteries]
681                          [BritishTVShows, Docuseries]
685                                              [Dramas]
688       [Comedies, InternationalMovies, RomanticMovies]
694                 [Comedies, Dramas, IndependentMovies]
698      [Dramas, IndependentMovies, InternationalMovies]
701                                              [Dramas]
702                 [Comedies, Dramas, IndependentMovies]
705     [Documentaries, InternationalMovies, SportsMov...
708                           [Dramas, IndependentMovies]
711              [Dramas, InternationalMovies, Thrillers]
716                                       [Documentaries]
718                         [Comedies, IndependentMovies]
721                                    [Action&Adventure]
722                                       [Documentaries]
723                                           [RealityTV]
726                                             [TVShows]
728                                        [HorrorMovies]
735               [Comedies, Dramas, InternationalMovies]
736     [Children&FamilyMovies, Dramas, InternationalM...
737                 [AnimeSeries, CrimeTVShows, TVHorror]
739                     [Children&FamilyMovies, Comedies]
740                              [Comedies, HorrorMovies]
741                         [Dramas, InternationalMovies]
742                         [Dramas, InternationalMovies]
743           [Dramas, IndependentMovies, RomanticMovies]
745                      [InternationalMovies, Thrillers]
746                                   [Dramas, Thrillers]
747               [Comedies, Dramas, InternationalMovies]
750      [Dramas, IndependentMovies, InternationalMovies]
752          [Action&Adventure, Comedies, Sci-Fi&Fantasy]
754                           [Dramas, IndependentMovies]
756         [Dramas, InternationalMovies, RomanticMovies]
757                                       [Documentaries]
758               [RomanticTVShows, TVComedies, TVDramas]
762       [Comedies, InternationalMovies, RomanticMovies]
764       [Comedies, InternationalMovies, RomanticMovies]
765               [Action&Adventure, InternationalMovies]
766                                      [Stand-UpComedy]
768               [Comedies, Dramas, InternationalMovies]
770     [Documentaries, InternationalMovies, Music&Mus...
773              [Dramas, InternationalMovies, Thrillers]
774          [Dramas, Faith&Spirituality, RomanticMovies]
775              [Dramas, IndependentMovies, LGBTQMovies]
776                                    [Action&Adventure]
777            [Comedies, IndependentMovies, LGBTQMovies]
779        [Action&Adventure, CultMovies, Sci-Fi&Fantasy]
782                              [Dramas, RomanticMovies]
783       [Comedies, InternationalMovies, Music&Musicals]
784                 [Comedies, Dramas, IndependentMovies]
786                            [Action&Adventure, Dramas]
787                                    [Action&Adventure]
788                                           [Thrillers]
790                                       [Documentaries]
791                            [Action&Adventure, Dramas]
792                    [Comedies, Dramas, RomanticMovies]

In [15]:
print(df['director'].iloc[0])
print(type(df['director'].iloc[0]))

Haile Gerima
<class 'str'>

In [16]:
df['director'] = df['director'].apply(lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else [])

In [17]:
print(df['director'].head(5))

7     []
8     []
9     []
12    []
24    []
Name: director, dtype: object

In [18]:
df.head(25)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,parsed_date
7,s8,Movie,Sankofa,[],"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24
8,s9,TV Show,The Great British Baking Show,[],"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24
9,s10,Movie,The Starling,[],"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021-09-24
12,s13,Movie,Je Suis Karl,[],"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,2021-09-23
24,s25,Movie,Jeans,[],"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,2021-09-21
27,s28,Movie,Grown Ups,[],"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...,2021-09-20
28,s29,Movie,Dark Skies,[],"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...,2021-09-19
29,s30,Movie,Paranoia,[],"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ...",2021-09-19
38,s39,Movie,Birth of the Dragon,[],"Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...","China, Canada, United States","September 16, 2021",2017,PG-13,96 min,"Action & Adventure, Dramas",A young Bruce Lee angers kung fu traditionalis...,2021-09-16
41,s42,Movie,Jaws,[],"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...,2021-09-16
42,s43,Movie,Jaws 2,[],"Roy Scheider, Lorraine Gary, Murray Hamilton, ...",United States,"September 16, 2021",1978,PG,116 min,"Dramas, Horror Movies, Thrillers",Four years after the last deadly shark attacks...,2021-09-16
43,s44,Movie,Jaws 3,[],"Dennis Quaid, Bess Armstrong, Simon MacCorkind...",United States,"September 16, 2021",1983,PG,98 min,"Action & Adventure, Horror Movies, Thrillers",After the staff of a marine theme park try to ...,2021-09-16
44,s45,Movie,Jaws: The Revenge,[],"Lorraine Gary, Lance Guest, Mario Van Peebles,...",United States,"September 16, 2021",1987,PG-13,91 min,"Action & Adventure, Horror Movies, Thrillers","After another deadly shark attack, Ellen Brody...",2021-09-16
46,s47,Movie,Safe House,[],"Denzel Washington, Ryan Reynolds, Vera Farmiga...","South Africa, United States, Japan","September 16, 2021",2012,R,115 min,Action & Adventure,Young CIA operative Matt Weston must get a dan...,2021-09-16
48,s49,Movie,Training Day,[],"Denzel Washington, Ethan Hawke, Scott Glenn, T...",United States,"September 16, 2021",2001,R,122 min,"Dramas, Thrillers",A rookie cop with one day to prove himself to ...,2021-09-16
51,s52,Movie,InuYasha the Movie 2: The Castle Beyond the Lo...,[],"Kappei Yamaguchi, Satsuki Yukino, Mieko Harada...",Japan,"September 15, 2021",2002,TV-14,99 min,"Action & Adventure, Anime Features, Internatio...","With their biggest foe seemingly defeated, Inu...",2021-09-15
52,s53,Movie,InuYasha the Movie 3: Swords of an Honorable R...,[],"Kappei Yamaguchi, Satsuki Yukino, Koji Tsujita...",Japan,"September 15, 2021",2003,TV-14,99 min,"Action & Adventure, Anime Features, Internatio...",The Great Dog Demon beaqueathed one of the Thr...,2021-09-15
53,s54,Movie,InuYasha the Movie 4: Fire on the Mystic Island,[],"Kappei Yamaguchi, Satsuki Yukino, Koji Tsujita...",Japan,"September 15, 2021",2004,TV-PG,88 min,"Action & Adventure, Anime Features, Internatio...","Ai, a young half-demon who has escaped from Ho...",2021-09-15
54,s55,Movie,InuYasha the Movie: Affections Touching Across...,[],"Kappei Yamaguchi, Satsuki Yukino, Koji Tsujita...",Japan,"September 15, 2021",2001,TV-PG,100 min,"Action & Adventure, Anime Features, Internatio...",A powerful demon has been sealed away for 200 ...,2021-09-15
56,s57,Movie,Naruto Shippuden the Movie: Blood Prison,[],"Junko Takeuchi, Chie Nakamura, Rikiya Koyama, ...",Japan,"September 15, 2021",2011,TV-14,102 min,"Action & Adventure, Anime Features, Internatio...",Mistakenly accused of an attack on the Fourth ...,2021-09-15
57,s58,Movie,Naruto Shippûden the Movie: Bonds,[],"Junko Takeuchi, Chie Nakamura, Noriaki Sugiyam...",Japan,"September 15, 2021",2008,TV-PG,93 min,"Action & Adventure, Anime Features, Internatio...",When strange ninjas ambush the village of Kono...,2021-09-15
58,s59,Movie,Naruto Shippûden the Movie: The Will of Fire,[],"Junko Takeuchi, Chie Nakamura, Kazuhiko Inoue,...",Japan,"September 15, 2021",2009,TV-PG,96 min,"Action & Adventure, Anime Features, Internatio...",When four out of five ninja villages are destr...,2021-09-15
59,s60,Movie,Naruto Shippuden: The Movie,[],"Junko Takeuchi, Chie Nakamura, Yoichi Masukawa...",Japan,"September 15, 2021",2007,TV-PG,95 min,"Action & Adventure, Anime Features, Internatio...",The adventures of adolescent ninja Naruto Uzum...,2021-09-15
60,s61,Movie,Naruto Shippuden: The Movie: The Lost Tower,[],"Junko Takeuchi, Chie Nakamura, Satoshi Hino, R...",Japan,"September 15, 2021",2010,TV-14,85 min,"Action & Adventure, Anime Features, Internatio...","When Naruto is sent to recover a missing nin, ...",2021-09-15
61,s62,Movie,Naruto the Movie 2: Legend of the Stone of Gelel,[],"Junko Takeuchi, Gamon Kaai, Chie Nakamura, Sho...",Japan,"September 15, 2021",2005,TV-PG,97 min,"Action & Adventure, Anime Features, Internatio...","While on a mission to return a missing pet, Na...",2021-09-15

In [ ]:
import pandas as pd

# Split cast column into a list
def preprocess_cast(df, col='cast'):
    df[col] = df[col].apply(lambda x: [i.strip() for i in x.split(",")] if isinstance(x, str) else [])
    return df

#Split country column into list
def preprocess_country(df, col='country'):
    df[col] = df[col].apply(lambda x: [i.strip() for i in x.split(",")] if isinstance(x, str) else [])
    return df

# Extract year, month, day_of_week from the parsed_date column
def add_date_features(df, col='parsed_date'):
    df['year_added'] = df[col].dt.year
    df['month_added'] = df[col].dt.month
    df['day_of_week'] = df[col].dt.day_name()
    return df

def preprocess_description(df, col='description', out_col='description_tokens'):
    df[out_col] = df[col].apply(
        lambda x: x.split() if isinstance(x, str) else []
    )
    return df

# Clean movie duration into numeric columns
def preprocess_duration(df, col='duration'):
    def convert_duration(val):
        if isinstance(val, str):
            if "min" in val:
                return int(val.replace("min", "").strip()), None
            elif "Season" in val:
                return None, int(val.replace("Seasons", "").replace("Season", "").strip())
        return None, None
    
    df['duration_minutes'], df['num_seasons'] = zip(*df[col].map(convert_duration))
    return df

# Split listed_in (genres) into a list
def preprocess_genres(df, col='listed_in'):
    df['genres'] = df[col].apply(lambda x: [i.strip() for i in x.split(",")] if isinstance(x, str) else [])
    return df

In [20]:
# Assuming df is your Netflix dataframe
df = preprocess_cast(df)
df = preprocess_country(df)
df = add_date_features(df)
df = preprocess_duration(df)
df = preprocess_description(df)
df = preprocess_genres(df)

In [21]:
df.head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,parsed_date,year_added,month_added,day_of_week,duration_minutes,num_seasons,description_tokens,genres
7,s8,Movie,Sankofa,[],"[Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra ...","[United States, Ghana, Burkina Faso, United Ki...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24,2021,9,Friday,125.0,NaN,"[On, a, photo, shoot, in, Ghana,, an, American...","[Dramas, Independent Movies, International Mov..."
8,s9,TV Show,The Great British Baking Show,[],"[Mel Giedroyc, Sue Perkins, Mary Berry, Paul H...",[United Kingdom],"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24,2021,9,Friday,NaN,9.0,"[A, talented, batch, of, amateur, bakers, face...","[British TV Shows, Reality TV]"
9,s10,Movie,The Starling,[],"[Melissa McCarthy, Chris O'Dowd, Kevin Kline, ...",[United States],"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021-09-24,2021,9,Friday,104.0,NaN,"[A, woman, adjusting, to, life, after, a, loss...","[Comedies, Dramas]"
12,s13,Movie,Je Suis Karl,[],"[Luna Wedler, Jannis Niewöhner, Milan Peschel,...","[Germany, Czech Republic]","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,2021-09-23,2021,9,Thursday,127.0,NaN,"[After, most, of, her, family, is, murdered, i...","[Dramas, International Movies]"
24,s25,Movie,Jeans,[],"[Prashanth, Aishwarya Rai Bachchan, Sri Lakshm...",[India],"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,2021-09-21,2021,9,Tuesday,166.0,NaN,"[When, the, father, of, the, man, she, loves, ...","[Comedies, International Movies, Romantic Movies]"
27,s28,Movie,Grown Ups,[],"[Adam Sandler, Kevin James, Chris Rock, David ...",[United States],"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...,2021-09-20,2021,9,Monday,103.0,NaN,"[Mourning, the, loss, of, their, beloved, juni...",[Comedies]
28,s29,Movie,Dark Skies,[],"[Keri Russell, Josh Hamilton, J.K. Simmons, Da...",[United States],"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...,2021-09-19,2021,9,Sunday,97.0,NaN,"[A, family’s, idyllic, suburban, life, shatter...","[Horror Movies, Sci-Fi & Fantasy]"
29,s30,Movie,Paranoia,[],"[Liam Hemsworth, Gary Oldman, Amber Heard, Har...","[United States, India, France]","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ...",2021-09-19,2021,9,Sunday,106.0,NaN,"[Blackmailed, by, his, company's, CEO,, a, low...",[Thrillers]
38,s39,Movie,Birth of the Dragon,[],"[Billy Magnussen, Ron Yuan, Qu Jingjing, Terry...","[China, Canada, United States]","September 16, 2021",2017,PG-13,96 min,"Action & Adventure, Dramas",A young Bruce Lee angers kung fu traditionalis...,2021-09-16,2021,9,Thursday,96.0,NaN,"[A, young, Bruce, Lee, angers, kung, fu, tradi...","[Action & Adventure, Dramas]"
41,s42,Movie,Jaws,[],"[Roy Scheider, Robert Shaw, Richard Dreyfuss, ...",[United States],"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...,2021-09-16,2021,9,Thursday,124.0,NaN,"[When, an, insatiable, great, white, shark, te...","[Action & Adventure, Classic Movies, Dramas]"
42,s43,Movie,Jaws 2,[],"[Roy Scheider, Lorraine Gary, Murray Hamilton,...",[United States],"September 16, 2021",1978,PG,116 min,"Dramas, Horror Movies, Thrillers",Four years after the last deadly shark attacks...,2021-09-16,2021,9,Thursday,116.0,NaN,"[Four, years, after, the, last, deadly, shark,...","[Dramas, Horror Movies, Thrillers]"
43,s44,Movie,Jaws 3,[],"[Dennis Quaid, Bess Armstrong, Simon MacCorkin...",[United States],"September 16, 2021",1983,PG,98 min,"Action & Adventure, Horror Movies, Thrillers",After the staff of a marine theme park try to ...,2021-09-16,2021,9,Thursday,98.0,NaN,"[After, the, staff, of, a, marine, theme, park...","[Action & Adventure, Horror Movies, Thrillers]"
44,s45,Movie,Jaws: The Revenge,[],"[Lorraine Gary, Lance Guest, Mario Van Peebles...",[United States],"September 16, 2021",1987,PG-13,91 min,"Action & Adventure, Horror Movies, Thrillers","After another deadly shark attack, Ellen Brody...",2021-09-16,2021,9,Thursday,91.0,NaN,"[After, another, deadly, shark, attack,, Ellen...","[Action & Adventure, Horror Movies, Thrillers]"
46,s47,Movie,Safe House,[],"[Denzel Washington, Ryan Reynolds, Vera Farmig...","[South Africa, United States, Japan]","September 16, 2021",2012,R,115 min,Action & Adventure,Young CIA operative Matt Weston must get a dan...,2021-09-16,2021,9,Thursday,115.0,NaN,"[Young, CIA, operative, Matt, Weston, must, ge...",[Action & Adventure]
48,s49,Movie,Training Day,[],"[Denzel Washington, Ethan Hawke, Scott Glenn, ...",[United States],"September 16, 2021",2001,R,122 min,"Dramas, Thrillers",A rookie cop with one day to prove himself to ...,2021-09-16,2021,9,Thursday,122.0,NaN,"[A, rookie, cop, with, one, day, to, prove, hi...","[Dramas, Thrillers]"
51,s52,Movie,InuYasha the Movie 2: The Castle Beyond the Lo...,[],"[Kappei Yamaguchi, Satsuki Yukino, Mieko Harad...",[Japan],"September 15, 2021",2002,TV-14,99 min,"Action & Adventure, Anime Features, Internatio...","With their biggest foe seemingly defeated, Inu...",2021-09-15,2021,9,Wednesday,99.0,NaN,"[With, their, biggest, foe, seemingly, defeate...","[Action & Adventure, Anime Features, Internati..."
52,s53,Movie,InuYasha the Movie 3: Swords of an Honorable R...,[],"[Kappei Yamaguchi, Satsuki Yukino, Koji Tsujit...",[Japan],"September 15, 2021",2003,TV-14,99 min,"Action & Adventure, Anime Features, Internatio...",The Great Dog Demon beaqueathed one of the Thr...,2021-09-15,2021,9,Wednesday,99.0,NaN,"[The, Great, Dog, Demon, beaqueathed, one, of,...","[Action & Adventure, Anime Features, Internati..."
53,s54,Movie,InuYasha the Movie 4: Fire on the Mystic Island,[],"[Kappei Yamaguchi, Satsuki Yukino, Koji Tsujit...",[Japan],"September 15, 2021",2004,TV-PG,88 min,"Action & Adventure, Anime Features, Internatio...","Ai, a young half-demon who has escaped from Ho...",2021-09-15,2021,9,Wednesday,88.0,NaN,"[Ai,, a, young, half-demon, who, has, escaped,...","[Action & Adventure, Anime Features, Internati..."
54,s55,Movie,InuYasha the Movie: Affections Touching Across...,[],"[Kappei Yamaguchi, Satsuki Yukino, Koji Tsujit...",[Japan],"September 15, 2021",2001,TV-PG,100 min,"Action & Adventure, Anime Features, Internatio...",A powerful demon has been sealed away for 200 ...,2021-09-15,2021,9,Wednesday,100.0,NaN,"[A, powerful, demon, has, been, sealed, away, ...","[Action & Adventure, Anime Features, Internati..."
56,s57,Movie,Naruto Shippuden the Movie: Blood Prison,[],"[Junko Takeuchi, Chie Nakamura, Rikiya Koyama,...",[Japan],"September 15, 2021",2011,TV-14,102 min,"Action & Adventure, Anime Features, Internatio...",Mistakenly accused of an attack on the Fourth ...,2021-09-15,2021,9,Wednesday,102.0,NaN,"[Mistakenly, accused, of, an, attack, on, the,...","[Action & Adventure, Anime Features, Internati..."

In [22]:
# Every row should now have proper list types:
assert df['cast'].map(lambda x: isinstance(x, list)).all()
assert df['country'].map(lambda x: isinstance(x, list)).all()
assert df['genres'].map(lambda x: isinstance(x, list)).all()
assert df['description_tokens'].map(lambda x: isinstance(x, list)).all()

# Duration columns should be nullable integers (or int if fillna_zero=True)
print(df['duration_minutes'].dtype, df['num_seasons'].dtype)

# Peek a few rows
print(df[['type','title','duration','duration_minutes','num_seasons','genres']].head())

float64 float64
       type                          title   duration  duration_minutes  \
7     Movie                        Sankofa    125 min             125.0
8   TV Show  The Great British Baking Show  9 Seasons               NaN
9     Movie                   The Starling    104 min             104.0
12    Movie                   Je Suis Karl    127 min             127.0
24    Movie                          Jeans    166 min             166.0

    num_seasons                                             genres
7           NaN  [Dramas, Independent Movies, International Mov...
8           9.0                     [British TV Shows, Reality TV]
9           NaN                                 [Comedies, Dramas]
12          NaN                     [Dramas, International Movies]
24          NaN  [Comedies, International Movies, Romantic Movies]

In [23]:
#Concatenation of multiple columns

df['tags'] =  df['description_tokens'] + df['genres'] + df['cast'] + df['director']

In [24]:
new_df = df[['show_id', 'title', 'tags']]

In [25]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\GOWTHAM\AppData\Local\Temp\ipykernel_40348\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [26]:
new_df.head(10)

,show_id,title,tags
7,s8,Sankofa,"On a photo shoot in Ghana, an American model s..."
8,s9,The Great British Baking Show,A talented batch of amateur bakers face off in...
9,s10,The Starling,A woman adjusting to life after a loss contend...
12,s13,Je Suis Karl,After most of her family is murdered in a terr...
24,s25,Jeans,When the father of the man she loves insists t...
27,s28,Grown Ups,Mourning the loss of their beloved junior high...
28,s29,Dark Skies,A family’s idyllic suburban life shatters when...
29,s30,Paranoia,"Blackmailed by his company's CEO, a low-level ..."
38,s39,Birth of the Dragon,A young Bruce Lee angers kung fu traditionalis...
41,s42,Jaws,When an insatiable great white shark terrorize...

In [36]:
new_df.to_pickle("new_movies.pkl")
print("Saved cleaned dataframe!")

Saved cleaned dataframe!

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

In [ ]:
mlb = MultiLabelBinarizer()
genre_matrix = mlb.fit_transform(df['listed_in'].str.split(', '))
genre_df = pd.DataFrame(genre_matrix, columns=mlb.classes_)

In [ ]:
df_final = pd.concat([df, genre_df], axis=1)

In [ ]:
df_final.columns

In [ ]:
print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())
print("\nDtypes:\n", df.dtypes)
print("\nMissing values:\n", df.isna().sum().sort_values(ascending=False))
print("\nDuplicates:", df.duplicated(subset=['title','type','release_year']).sum())

In [ ]:
for col in ['title', 'director', 'cast', 'country', 'listed_in', 'rating', 'description']:
    if col in df_final.columns:
        df_final[col] = df_final[col].astype(str).str.strip().replace({'nan':'', 'None':''})

In [ ]:
## Find similarity between movies

from sklearn.metrics.pairwise import cosine_similarity
cos_sim_matrix = cosine_similarity(genre_df.values)

In [ ]:
sim_df = pd.DataFrame(cos_sim_matrix, index=df['title'], columns=df['title'])
print(sim_df.tail(10))

In [ ]:
print(sim_df.index[:20])

In [ ]:
def recommend_movie(movie_title, sim_matrix, top_n=5):
    if movie_title not in sim_matrix.columns:
        return f"Movie '{movie_title}' not found in dataset!"
    
    similar_movies = sim_matrix[movie_title].sort_values(ascending=False)
    return similar_movies.iloc[1:top_n+1]
    
print(recommend_movie("The Darkest Hour", sim_df, top_n=3))

In [ ]:
print(recommend_movie("2012", sim_df, top_n=10))

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

def build_similarity_matrix(df):
    tfidf = TfidfVectorizer(stop_words="english")
    tfidf_matrix = tfidf.fit_transform(df['features'])
    cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
    return cosine_sim

In [3]:
import pandas as pd

def recommend_movie(title, df, cosine_sim, top_n=10):
    title = title.lower().strip()
    indices = pd.Series(df.index, index=df['title']).drop_duplicates()
    
    if title not in indices:
        return f"'{title}' not found in dataset."
    
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]  # skip itself
    
    movie_indices = [i[0] for i in sim_scores]
    return df['title'].iloc[movie_indices]

In [11]:
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath('.')))

In [13]:
def recommend_movie(movie_name, sim_df, top_n=10):
    movie_name = movie_name.lower().strip()
    if movie_name not in sim_df.index:
        return "Movie not found in dataset."

    # Sort similar movies
    similar_scores = sim_df[movie_name].sort_values(ascending=False)
    
    # Exclude the movie itself
    recommendations = similar_scores.iloc[1:top_n+1]
    return recommendations

# Example
print(recommend_movie("the lord of the rings: the two towers", sim_df, 5))

NameError: name 'sim_df' is not defined